baseURL = "http://www.masocal.org/"
title = "MA Socal"
theme = "jane"

buildDrafts = true
buildFuture = true

publishDir = "_public"
resourceDir = "_resources"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

paginate = 3
# rssLimit = 20
# disqusShortname = ""
# googleAnalytics = ""
# copyright = ""

verbose = true
watch = true
publishdir = "_public"

defaultContentLanguage = "en"
[languages.en]
  languageCode = "en"

[frontmatter]
  lastmod = [":git", ":fileModTime", ":default"]

[author]
  name = "MA Socal"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
