baseURL = "http://www.masocal.org/"
title = "MA Socal"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

paginate = 3
# rssLimit = 20
# disqusShortname = ""
# googleAnalytics = ""
# copyright = ""
enableGitInfo = true

verbose = true
watch = true
publishdir = "_public"

defaultContentLanguage = "en"
[languages.en]
  languageCode = "en"

[frontmatter]
  lastmod = [":git", ":fileModTime", ":default"]

[author]
  name = "MA Socal"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
