debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
since = "2019"            # Site creation time
homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
rssFullContent = true     # if false, Rss feed instead of the summary
mainSections = ["post"]

# site info (optional)
logoTitle = "MA Socal"        # default: the title value
keywords = ["recovery", "12-steps", "twelve-step", "marijuana", "anonymous"]
description = "Marijuana Anonymous of Southern California"

# paginate of archives, tags and categories
archive-paginate = 3

# paginate style, default use numbered pagination links
# if true, use original "Previous" and "Next" links.
# paginateOriginalStyle = true

# The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
dateFormatToUse = "2006-01-02"

# show word count and read time ?
moreMeta = false

# show language chooser in menu
showMenuLanguageChooser = false

showAuthorInfo = true # show author info below the article

# Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
toc = true
photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe
bootcdn = false           # In china. @Deprecated: use [params.publicCDN]
mathjax = false           # see https://www.mathjax.org/
katex = false             # see https://github.com/KaTeX/KaTeX
contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

changyanAppid = ""        # Changyan app id
changyanAppkey = ""       # Changyan app key
tencent_analytics = ""    # Tencent Analytics
baidu_push = false        # baidu push
baidu_analytics = ""      # Baidu Analytics
baidu_verification = ""   # Baidu Verification
google_verification = ""  # Google_Verification

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

# enable 'fork me on github', see https://blog.github.com/2008-12-19-github-ribbons/
# forkMeOnGithub = "https://github.com/xianmin/hugo-theme-jane"

# add custom info on the footer.
# customFooter = "Grown from digitalr00ts."

[publicCDN]        # load these files from public cdn
  enable = false
  jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
  slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
  gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
  gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'
  photoswipe = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.js" integrity="sha256-AC9ChpELidrhGHX23ZU53vmRdz3FhKaN9E28+BbcWBw=" crossorigin="anonymous"></script>'
  photoswipeUI = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js" integrity="sha256-UKkzOn/w1mBxRmLLGrSeyB4e1xbrp4xylgAWb3M42pU=" crossorigin="anonymous"></script>'
  photoswipeCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.css" integrity="sha256-SBLU4vv6CA6lHsZ1XyTdhyjJxCjPif/TRkjnsyGAGnE=" crossorigin="anonymous">'
  photoswipeSKIN = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/default-skin/default-skin.css" integrity="sha256-c0uckgykQ9v5k+IqViZOZKc47Jn7KQil4/MP3ySA3F8=" crossorigin="anonymous">'

[utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
  enable = false
  repo = "xianmin/comments-for-hugo-theme-jane"    # The repo to store comments
  issueTerm = "pathname"

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[livere]          	#LiveRe comment. see https://www.livere.com/
  uid = ""

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = ''
  appKey = ''
  notify = false  # If you are using valine-admin(https://github.com/DesertsP/Valine-Admin) to notify users, do NOT enable this.
  verify = false # Verification code
  avatar = 'mm'
  placeholder = ''

[search.google]    # google custom search, see https://cse.google.com
  enable = false
  id = "002186711602136249422:q1gkomof_em"
  title = "Search"

[reward]
  enable = false
  wechat = "/path/to/your/wechat-qr-code.png"
  alipay = "/path/to/your/alipay-qr-code.png"

[counter.busuanzi]  # a Chinese visitor counter
  enable = false

[counter.leancloud]  # Chinese leancloud visitor counter
  enable = false
  appId = ""
  appKey = ""

[commentCount.disqus] # show counts of comments for Disqus
  enable = false

# use public git repo url to link lastmod git commit, enableGitInfo should be true.
[gitInfo]
  gitRepo = "https://github.com/xianmin/hugo-theme-jane"
  showCommitMessage = true

[social]
#  a-email = "mailto:your@email.com"
#     b-stack-overflow = "http://localhost:1313"
#     c-twitter = "http://localhost:1313"
#     d-facebook = "http://localhost:1313"
#     e-linkedin = "http://localhost:1313"
#     f-google = "http://localhost:1313"
#     g-github = "http://localhost:1313"
#     h-weibo = "http://localhost:1313"
#     i-zhihu = "http://localhost:1313"
#     j-douban = "http://localhost:1313"
#     k-pocket = "http://localhost:1313"
#     l-tumblr = "http://localhost:1313"
#     m-instagram = "http://localhost:1313"
#     n-gitlab = "http://localhost:1313"
#     o-goodreads = "http://localhost:1313"
#     p-coding = "http://localhost:1313"
#     q-bilibili = "http://localhost:1313"
#     r-codeforces = "http://localhost:1313"

# jsonfeed support
# more information: https://github.com/xianmin/hugo-theme-jane/issues/23
# to have json output it's necessary to uncomment this block of code and create a index.jsonfeed.json template, using hugo template specs
# [outputs]
#   home = ["html", "jsonfeed","rss"]
#   page = ["html"]
#
# [outputFormats]
# [outputFormats.jsonfeed]
#   mediaType = "application/json"
#   baseName = "feed"
#   isPlainText = true


# multilingual support example
# [langusges]
# [languages.en]
#   title = "Jane - A simple theme for Hugo"
#   weight = 1
# [languages.zh-cn]
#   title = "Jane —— 一个简洁的 Hugo 主题"
#   weight = 2
