---
default:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  before_script:
  - apk add --update git npm
  - npm install -D

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  stage: stage
  script:
  - hugo --environment production
  - >-
    printf "Disallow: /*\n" > public/robot.txt
  artifacts:
    paths:
    - public
  environment:
      name: staging
      url: ${CI_PAGES_URL}
  only:
  - master

stages:
  - test
  - stage
  # - deploy
