---
image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  before_script:
  - apk add --update git npm
  - npm install -D

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo --environment production
  - >-
    printf "Disallow: /*\n" > public/robot.txt
  artifacts:
    paths:
    - public
  environment:
      name: staging
      url: ${CI_PAGES_URL}
  only:
  - master